name: ${project.name}
version: ${project.version}
description: Set time windows per player when they are allowed to be online
author: Rich Alberth
website: https://dev.bukkit.org/projects/player-time-window
main: com.github.ralberth.playertimewindow.PlayerTimeWindow
database: false

commands:
  timewindows:
    description: Show what times you are allowed to play
    usage: /timewindows [list|enable|disable <duration>|status]

permissions:
  # !!! the name here must agree with the constant in CommandLine.java!
  playertimewindow.enabledisable:
    description: Allows you to turn on/off the PlayerTimeWindows plugin
    default: false
